name: Serve-InvenioRDM checks

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - "Dockerfile"
      - "custom_*.py"
      - "tests/**"
      - ".github/workflows/serve-inveniordm.yml"

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Build test image'
        run: |
          docker build -t ghcr.io/scilifelabdatacentre/serve-inveniordm:latest .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: 'ghcr.io/scilifelabdatacentre/serve-inveniordm:latest'
          format: 'table'
          severity: 'CRITICAL,HIGH'
          timeout: '30m0s'
          exit-code: '0'

      - name: 'Run tests'
        env:
          IMAGE_NAME: ghcr.io/scilifelabdatacentre/serve-inveniordm:latest
        run: |
          pip install -r ./tests/requirements.txt
          python3 -m pytest .
